### ISSUE TITLE
It Doesn't Work

### ISSUE THREAD

**Issue by fluttyCat** [wwdablu/SimplyPDF#34]
when I import the library into my project, it did not be imported and I can't create an object of simplyPdf

**Comment by wwdablu** [comment]
@fluttyCat  Can you share me the code which is causing the issue. I can take a look into it.

**Comment by fluttyCat** [comment]
Yeah sure

![image](https://user-images.githubusercontent.com/48894215/181907973-d3ec662b-f086-44d1-8432-4dd40a2e6fec.png)

![image](https://user-images.githubusercontent.com/48894215/181908007-f7bee1bb-44cf-45b5-a45d-ccc048c5cda9.png)

**Comment by wwdablu** [comment]
Looking into the reported issue.

**Comment by wwdablu** [comment]
`SimplyPdf.with(this, File(""))
            .colorMode(DocumentInfo.ColorMode.COLOR)
            .paperSize(PrintAttributes.MediaSize.ISO_A4)
            .margin(Margin.default)
            .firstPageBackgroundColor(Color.WHITE)
            .paperOrientation(DocumentInfo.Orientation.PORTRAIT)
            .build()`

Can you use the above code. The example provided in the readme is not updated as per the latest release. Will correct.

**Comment by fluttyCat** [comment]
I did everything you said but here is the result
![image](https://user-images.githubusercontent.com/48894215/181909629-c0f6700f-1815-4d1e-b4ae-c75a9c9b3c04.png)

**Comment by wwdablu** [comment]
@fluttyCat  Interesting! Is it possible for you to commit the code in GitHub and share me the link. I can execute the code locally to identify the issue.

**Comment by fluttyCat** [comment]
It's okay with me but its the company code and they have some policies unfortunately

**Comment by wwdablu** [comment]
Okay, understandable. Then you can git clone SimplyPDF and execute the sample provided with this project. Can you confirm if that is working for you.

**Comment by fluttyCat** [comment]
yes sure, i will let you know

**Comment by wwdablu** [comment]
Closing it, considering that it worked.

**Comment by fluttyCat** [comment]
Hi, you just need add an empty header to builder :D
