### ISSUE TITLE
Add possibility to write text at the position

### ISSUE THREAD

**Issue by Yury-D** [wwdablu/SimplyPDF#35]
Hi. Thanks for the your cool library. It would be nice to add possibility to write text at the position. What do you think?

**Comment by Yury-D** [comment]
I can do that if you dont mind

**Comment by wwdablu** [comment]
Sure. You can create a PR if you like.

**Comment by wwdablu** [comment]
PR raised by @Yury-D has been merged to master branch.
https://github.com/wwdablu/SimplyPDF/pull/36
