### ISSUE TITLE
Choose custom location for save the generated PDF

### ISSUE THREAD

**Issue by aravindh2106** [wwdablu/SimplyPDF#37]
- How to store pdf in different location? Until now i couldn't find any way.

**Comment by wwdablu** [comment]
When you are creating the PDF Document you can specify a file object to the location that you want. For example to store it in the external directory.

simplyPdfDocument = SimplyPdf.with(this, new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/test.pdf"))
    .colorMode(DocumentInfo.ColorMode.COLOR)
    .paperSize(PrintAttributes.MediaSize.ISO_A4)
    .margin(Margin(startMargin, topMargin, endMargin, bottomMargin)
    .pageModifier(PageHeader())
    .firstPageBackgroundColor(Color.WHITE)
    .paperOrientation(DocumentInfo.Orientation.PORTRAIT)
    .build();
