### ISSUE TITLE
Add Header and Footer for each page.

### ISSUE THREAD

**Issue by anupambhardwaj** [wwdablu/SimplyPDF#38]
Hi,
How can we add a header and footer for each page with this library?

**Comment by wwdablu** [comment]
Hi @anupambhardwaj 

You can use the property `pageModifier`. For example you can use the PageHeader modified to add headers for all the pages.
```
.pageModifier(PageHeader(LinkedList<Cell>().apply {
                add(TextCell("PDF Generated Using SimplyPDF", TextProperties().apply {
                    textSize = 24
                    alignment = Layout.Alignment.ALIGN_CENTER
                    textColor = "#000000"
                }, Cell.MATCH_PARENT))
                add(TextCell("Version 2.1.0", TextProperties().apply {
                    textSize = 18
                    alignment = Layout.Alignment.ALIGN_CENTER
                    textColor = "#000000"
                }, Cell.MATCH_PARENT))
            }))
```

Similarly you can create your own Footer class by extending the PageModifier class and add it to the pageModifier when creating the pdf document. SimplyPDF will ensure to render them.

Note: Adding footer means that the usable page height needs to be calculated before rendering. If you still need the feature let me know I can add it as an enhancement.

Int he sample application you can observe the example. There is a pageModifier to add a line after the page header. For footer, you need to translate the canvas Y-axis inside the render function. Once the rendering is done, revert the Y translate back to the old contentHeight.
